export default {
	data() {
		return {
			shareData:[
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_postcard.png',
					name:'生成海报',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_wechat.png',
					name:'微信好友',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_wechatmoments.png',
					name:'朋友圈',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_qq.png',
					name:'QQ',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_qzone.png',
					name:'QQ空间',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_weibo.png',
					name:'微博',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_friend_in_mfw_pic.png',
					name:'站内好友',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_links.png',
					name:'复制链接',
					isShow:true,
				},
				{
					imgurl:'/uni_modules/FatFatMeng-PopupShare/static/FatFatMeng-apps/images/share/ic_share_save.png',
					name:'下载',
					isShow:true,
				},
			]
		}
	}
}